# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  
  lane :internal do
    update_fastlane
  end
  
  lane :beta do
    increment_build_number(xcodeproj: "Foodienator.xcodeproj")


    disable_automatic_code_signing
    update_project_provisioning(
      xcodeproj: "Foodienator.xcodeproj",
      profile: "com.fastlane.example.#{options[:id]}.mobileprovision",
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )
    update_project_team(
      path: "Project.xcodeproj",
      teamid: options[:team_id]
    )


    build_app(workspace: "Foodienator.xcworkspace", scheme: "Foodienator")
    upload_to_testflight(
      team_id:'7639N3C25S',
    )
  end

  lane :get_app_store_connect_api_key do
   app_store_connect_api_key(
     key_id: "58T684WNPZ", #Your Auth key ID
     issuer_id: "9389fe93-4b9b-4ba5-bff5-0470887755f9",#Your Auth key Issuer ID
     key_filepath: "fastlane/AuthKey_58T684WNPZ.p8",
     in_house: false,
   )
 end
 
 desc "Increment version prod"
 lane :increment_version do

   final_build_number =  increment_build_number
   final_version = get_version_number     
 
   puts "Final Version " + final_version
   puts "Final Build Number " + final_build_number
   ENV["VERSION"] = final_version
   ENV["BUILD_NUMBER"] = final_build_number
 end

     
 #builds app
 lane :build_to_testflight do
 
  puts "Preparing TestFlight Build - Make sure you have updated the Build Version & Number Otherwise Testflight will reject it."

  sigh(api_key: get_app_store_connect_api_key , app_identifier: "org.reactjs.native.example.Foodienator") #Replace with Your package name

  ipa = gym(
    scheme: "Foodienator", #Replace with Your scheme
    workspace: "Foodienator.xcworkspace", #Replace with Your workspace
    export_method: "app-store",
    output_directory: "build",
  )
  puts "Pushing build to testflight"
  pilot(
    api_key: get_app_store_connect_api_key,
    ipa: ipa,
    app_identifier: "org.reactjs.native.example.Foodienator",
    skip_waiting_for_build_processing: true,
    skip_submission: true,
    distribute_external: false,
    notify_external_testers: false,
    team_id: '7639N3C25S',
  )
   puts "Testflight Build Succeed"
 end
end